BoxLayout:
    padding: 10
    spacing: 10
    orientation: 'vertical'
    Label:
        text: "Jouer avec les verbes \nirréguliers par :"
        color: 1,1,1,1
        canvas.before:
            Color:
                rgba: 0.99, 0.65, 0.07, 1
            Rectangle:
                pos: self.pos
                size: self.size
    BoxLayout:
        orientation: 'horizontal'
        spacing: 10

        Button:
            text: "L'infinitif"
            size_hint: 1, 1
            background_color: 0.81, 0.27, 0.33, 1

        Button:
            text: "La traduction \nFrançaise"
            size_hint: 1, 1
