BoxLayout:
    padding: 10
    spacing: 10
    orientation: 'vertical'
    Label:
        text: "Jouer avec les verbes \nirréguliers par :"
        color: 1,1,1,1 # <-----------
        canvas.before:
            Color:
                rgba: 0.99, 0.65, 0.07, 1
            Rectangle:
                pos: self.pos
                size: self.size
BoxLayout:
    orientation: 'horizontal'
    spacing: 10

    Button:
        text: "L'infinitif"
        size_hint: 1, 1
        background_color: 0.81, 0.27, 0.33, 1

    Button:
        text: "La traduction \nFrançaise"
        size_hint: 1, 1
Label:
    height: "40dp"
    text: "Combien de parties \nvoulez-vous jouer?"
    color: 1,1,1,1 # <-----------
    canvas.before:
        Color:
            rgba: 0.99, 0.65, 0.07, 1
        Rectangle:
            pos: self.pos
            size: self.size
BoxLayout:
    orientation: 'horizontal'
    spacing: 2
    Button:
        text: "5"
        size_hint: 1, 1
    Button:
        text: "10"
        size_hint: 1, 1
    Button:
        text: "15"
        size_hint: 1, 1
    Button:
        text: "20"
        size_hint: 1, 1
BoxLayout:
    orientation: 'horizontal'
    spacing: 10
    Button:
        text: "Mode entrainement"
        size_hint: 1, 1
