BoxLayout:
    orientation: "vertical"
    padding: 20
    spacing: 10
    Button:
        text: "Bouton 1"
        size_hint: 1, 0.5
    Button:
        text: "Bouton 2"
        size_hint: 1, 0.25
    Button:
        text: "Bouton 3"
        size_hint: 1, 0.25
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Bouton 4"
            size_hint: 1, 1
        BoxLayout:
            orientation: "vertical"
            Button:
                text: "Bouton 5"
                size_hint: 0.5, 0.5
            Button:
                text: "Bouton 6"
                size_hint: 0.5, 0.5
